### PR TITLE
Added center map and fixed compile error

### LINKED ISSUE #39: Center Map on Launch
When MaizeBus is launched, it should open the map to the user's location by default instead of Ann Arbor.

### PR DESCRIPTION
**Pull request by gusrod-coder**
Added centering for map (on app start, or directly after the user declares that they will allow location tracking) - Edited build gradle and settings gradle to remove compiling error (kotlin 2.3 instead of 2.1).

### CODE REVIEW

File: lib/screens/map_screen.dart [hunk 1]
```diff
@@ -1942,6 +1942,7 @@ class _MaizeBusCoreState extends State<MaizeBusCore> {
       }
 
       Position? position = await Geolocator.getLastKnownPosition();
+      _centerOnLocation(true);
```
Comment (TheStaticBits) [inline lib/screens/map_screen.dart]: _centerOnLocation calls _getLastKnownLocation, creating an infinite loop.

File: lib/screens/map_screen.dart [hunk 2]
```diff
@@ -312,6 +307,10 @@ class _MaizeBusCoreState extends State<MaizeBusCore> {
     busProvider.startBusUpdates();
     busProvider.startRouteUpdates();
     await Future.delayed(const Duration(milliseconds: 180));
+
+    // Center map on user's location on startup if available
```
Comment (TheStaticBits) [inline lib/screens/map_screen.dart]: unnecessary comment

**Review by TheStaticBits — CHANGES_REQUESTED** [review]
you've created an infinite centerOnLocation loop -- make sure to run and test your features before creating a pull request. See comments for more details

**Comment by gusrod-coder** [comment]
Moved the center on location call to avoid infinite loops - Now will center once after user changes their geolocator permission from denied to allowed or on app open

**Review by TheStaticBits — COMMENTED** [review]
looks all good to me, aside from some buggy center-looping behavior when the user denies permissions -- but I think fixing the experience of using the app with location permissions denied should be another task entirely, since right now it spams the "location perms denied" banner regardless of this particular pull request. I'll approve this if @i-kumar is alright with it

**Comment by i-kumar** [comment]
checking it now

**Review by i-kumar — CHANGES_REQUESTED** [review]
Nope. Not the behavior we want. The centering after accepting location permissions for the first time is fine. But for the normal case, make it so that the map is centered when the map is loaded. If the app loads, and then the map animates there, it looks odd.

Right now the map is set to default center on ann arbor. You'll have to change that. And you'll have to write the call to find the location in the loading sequence (in `_loadAllData()`).

**Comment by gusrod-coder** [comment]
Code has been updated to update the starting location of the map before loading it when user has already provided location, should be good for review

**Review by TheStaticBits — APPROVED** [review]
looks good to me

**Comment by gusrod-coder** [comment]
MY GOAT

**Review by i-kumar — APPROVED** [review]
works on ios
